version: "1"

services:
  backend:
    image: python
    volumes:
      - ./:/app/backend
    working_dir: /app/backend
    ports:
      - 8000:8000
    command: bash -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"
